spring:
#  main:
#    lazy-initialization: true # 지연 초기화 활성화 (필요 없으면 제거)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}?rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

storage:
  endpoint: ${STORAGE_ENDPOINT}
  bucket: ${STORAGE_BUCKET}
  region: ${STORAGE_REGION}
  credentials:
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}

encryption:
  user-snapshot:
    public-key: ${USER_SNAPSHOT_ENCRYPTION_PUBLIC_KEY}

maxmind:
  geolite:
    path: file:/app/data/GeoLite2-City.mmdb

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.flyby.ramble: DEBUG # 애플리케이션 로깅
